name: Spring Boot Application ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 788155875213.dkr.ecr.ap-south-1.amazonaws.com
      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 788155875213.dkr.ecr.ap-south-1.amazonaws.com/springboot:${{ github.sha }}
      - name: Deploy to ECS
        uses: appleboy/ecs-deploy@v2.4.4
        with:
          region: ap-south-1
          service: springboot-service
          cluster: springboot-cluster
          image: 788155875213.dkr.ecr.ap-south-1.amazonaws.com/springboot:${{ github.sha }}

